/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.practico6;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Familia
 */
public class ConsultaporPrecio extends javax.swing.JInternalFrame {
private DefaultTableModel prec= new DefaultTableModel();
    /**
     * Creates new form ConsultaporPrecio
     */
    public ConsultaporPrecio() {
        initComponents();
        ArmarCabezera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTmenor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTmayor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTlistpre = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel1.setText("Listado de productos por precio");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Entre");

        jTmenor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTmenorKeyReleased(evt);
            }
        });

        jLabel3.setText("y");

        jTmayor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTmayorKeyReleased(evt);
            }
        });

        jTlistpre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTlistpre);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(196, 196, 196))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTmenor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTmayor, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTmenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTmayor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTmenorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTmenorKeyReleased
        // TODO add your handling code here:
        Limpiar();
        try {
            int menor = Integer.parseInt(jTmenor.getText());
            int mayor = Integer.parseInt(jTmayor.getText());
            for (Producto pm: MenuGeneral.lista) {
                if (pm.getPrecio()>= menor && pm.getPrecio()<=mayor) {
                    prec.addRow(new Object[]{
                        pm.getCodigo(),
                        pm.getDescripcion(),
                        pm.getPrecio(),
                        pm.getStock()
           
        });
                }
            }
        } catch (NumberFormatException e) {
            if (jTmenor.getText()== null ) {
                jTmenor.setText("0");
            }else if (jTmayor.getText()== null) {
                jTmayor.setText("0");
            }
        }
        
    }//GEN-LAST:event_jTmenorKeyReleased

    private void jTmayorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTmayorKeyReleased
        // TODO add your handling code here:
        Limpiar();
         try {
            int menor = Integer.parseInt(jTmenor.getText());
            int mayor = Integer.parseInt(jTmayor.getText());
            for (Producto pm: MenuGeneral.lista) {
                if (pm.getPrecio()>= menor && pm.getPrecio()<=mayor) {
                    prec.addRow(new Object[]{
                        pm.getCodigo(),
                        pm.getDescripcion(),
                        pm.getPrecio(),
                        pm.getStock()
           
        });
                }
            }
        } catch (NumberFormatException e) {
            if (jTmenor.getText()== null ) {
                jTmenor.setText("0");
            }else if (jTmayor.getText()== null) {
                jTmayor.setText("0");
            }
        }
    }//GEN-LAST:event_jTmayorKeyReleased
private void ArmarCabezera(){
prec.addColumn("Código");
prec.addColumn("Descripción");
prec.addColumn("Precio");
prec.addColumn("Stock");
jTlistpre.setModel(prec);}
public void Limpiar(){
int b = prec.getRowCount()-1;
    for (;b>=0; b--) {
        prec.removeRow(b);
    }}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTlistpre;
    private javax.swing.JTextField jTmayor;
    private javax.swing.JTextField jTmenor;
    // End of variables declaration//GEN-END:variables
}
